### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by drnoa** [schemaspy/schemaspy#206] opened 2017-12-20 08:39 UTC
Hi,

The original schemaspy code (https://sourceforge.net/projects/schemaspy/) was under GPL v2. So in my opinion its not allowed to change the licence to an MIT licence.
There's no way you can rescind the GPL on the software you have already given someone. The only way that license is allowed to be changed is to a newer version of the GPL.

**Comment by npetzall** [comment] 2017-12-20 11:58
Just a small correction it's not GPL it's LGPL for the original. I makes a difference.

**Comment by npetzall** [comment] 2017-12-20 12:10
Both LGPL and MIT allows commercial use so, do we have any need for MIT, since I think drnoa is correct. I wonder if it's OK to re-licence from LGPL to GPL as drnoa has done in his fork.

But I think we might need to take a close look at our dependencies and figure-out if we use GPL and need to GPL the whole application.

**Comment by drnoa** [comment] 2017-12-20 12:32
LGPL and GPL should not be a problem.

GNU Lesser General Public License: Permissions of this copyleft license are conditioned on making available complete source code of licensed works and modifications under the same license or the GNU GPL

https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

**Comment by rafalkasa** [comment] 2017-12-20 14:00
@drnoa thank you for your time and information about the original SchemaSpy code (https://sourceforge.net/projects/schemaspy/) license. I'm afraid that you have right and we should change back from MIT to GPL.

I'd like to move SchemaSpy to the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) license instead of MIT, but need contributors approval to do so as the code, tests and documentation we were provided under the MIT.

If you're on the list, please reply to this issue with a +1 if you're fine with the license change. No reply to January 31th 2018 will be considered as +1.

**Contributors:**

- @rafalkasa
- @npetzall
- @Riggs333
- @wkasa
- @danwatt
- @ismailsimsek
- @mapausch
- @ClintEstwood
- @martenbohlin
- @jornh
- @dhermanns
- @igor-suhorukov

**Comment by rafalkasa** [comment] 2017-12-20 14:01
+1

**Comment by martenbohlin** [comment] 2017-12-20 14:19
+1

**Comment by wkasa** [comment] 2017-12-20 14:47
+1

**Comment by dhermanns** [comment] 2017-12-20 15:53
+1
Wojciech Kasa <notifications@github.com> schrieb am Mi. 20. Dez. 2017 um
15:47:

**Comment by ismailsimsek** [comment] 2017-12-20 16:30
+1

**Comment by drnoa** [comment] 2017-12-20 19:51
Thank you for the project and your work anyway! Its nice to see people working on it and its going on!

**Comment by npetzall** [comment] 2017-12-20 19:59
+1

**Comment by igor-suhorukov** [comment] 2017-12-20 20:06
+1

**Comment by danwatt** [comment] 2017-12-20 20:52
+1

**Comment by mapausch** [comment] 2017-12-20 21:32
If every contributor agrees, than license can be changed to any other license.
If only some contributors agree, than source code from non-agreeing contributors have to be rewritten.
Relicensing will create a new "version" of the software. Older versions, of course, will still be "old-licensed". Newer version of the software will be under new license.

So maybe it makes sense to check if johncurrier (http://sourceforge.net/users/johncurrier) was the only contributor to "old" schemaspy and ask him if he would agree the relicensing.

I'm not a lawyer, but I can imagine that also upgradeing from GPLv2 to v3 needs approval of all contributors.

**Comment by Riggs333** [comment] 2017-12-20 22:44
+1

**Comment by rafalkasa** [comment] 2017-12-21 09:34
@mapausch I can confirm that johncurrier was only the author on https://sourceforge.net/projects/schemaspy/. 

![image](https://user-images.githubusercontent.com/19885116/34249468-1f2ccc92-e63a-11e7-950b-a2958ec95334.png)

Before I start working and continue SchemaSpy project I try to contact few times with John but he didn't answer of any of my emails and also he never add comments or create the change in original project since 2014. I keep my fingers crossed for everyone contributors to agree the license change.

@mapausch what is your decision ?

**Comment by npetzall** [comment] 2017-12-22 12:37
I've read most part of GPLv3 and it seems we must add addition copyright information and maybe an authors list in every source-file.

Since that information is only present in github, and will be lost in copy.
Also need to clearly mark that we have modified the files, so that original author won't be accountable for our changes.

But there were lots of other stuff thats required also, so might be good if everyone reads it or if someone that truly knows GPLv3 can guide at least me.

Also seems from the compatability matrix drnoa linked that LGPLv2.1 or later can be conveyed under GPLv3.

**Comment by rafalkasa** [comment] 2017-12-22 12:44
if I'm honest, I'm not a lawyer and I do not know too much about the opensource licenses. For me we can stay also on the same license as original project used. Adding author and copyright information and authors, exist also in GPLv2 as I know. I would like switch to GPLv3 from some reasons new version was created 😄

**Comment by jornh** [comment] 2017-12-23 09:52
+1

**Comment by npetzall** [comment] 2017-12-29 12:44
Probably need to update the CONTRIBUTING.md

I wonder if one can state that creating a pull request is surrendering Copyright to the project. This would make it simpler in the future regarding licensing. Since the copyright holder decides.

It's easier with just Copyright 2017-2018 SchemaSpy project than each individual. (John Currier will still be present)
And claim-for-fame is the (at)author at class definition.

But this is just to avoid a 13 line Copyright segment, it's totally fine in intelliJ since it collapse the first comment to one line.

**Comment by npetzall** [comment] 2017-12-30 14:05
https://www.gnu.org/licenses/lgpl-java.html

So we might want to go for LGPLv3 instead of GPL. Since #157 is about making it available in maven as a library and the user says they use 5.0 in their application. Which is OK, 5.0 is LGPL.

I'm just assuming that it's allowed in LGPL and not GPL. Based on the article.

**Comment by npetzall** [comment] 2018-04-05 19:10
@rafalkasa Should we go for LGPLv3 or later which is totally fine since original is LGPLv2 or later.
If so we probably need a new OK since the previous was for GPLv3.

We follow up on the answers and any code that needs to be re-written is created as a issue. And I'll get right on it.

**Comment by npetzall** [comment] 2018-04-15 21:29
The project as a whole needs to be licensed/distributer/conveyed under "LGPLv3" or "LGPLv3 or later"
Since at least one dependency has Apache 2.0 license.
MIT and LGPLv2.1 or later can be licensed/distributed/conveyed under "LGPLv3" or "LGPLv3 or later"

So we need to correct some texts that says MIT and have it say "LGPLv3 or later".
Any source code-file missing license should have MIT notice (implicit) unless issue #305 has received a comment granting us the contributions under LGPLv3 or later.

And then we should be done with this.

**Comment by npetzall** [comment] 2018-05-23 10:26
Fixed by #305

**Closed by npetzall** 2018-05-23 10:26 UTC
Labels: help wanted, important, question
