### ISSUE TITLE
Unable to find layout/schemaSpy.css 

### ISSUE THREAD

**Issue by saihegde** [schemaspy/schemaspy#26] opened 2017-01-03 18:11 UTC
Writing or graphing the summary out fails with the error message 

Unable to find requested file schemaspy-6.0.0-beta.2.jar!\layout\schemaSpy.css

**Comment by rafalkasa** [comment] 2017-01-03 18:28
Hi @saihegde I confirm this bug it will be fixed today

**Comment by rafalkasa** [comment] 2017-01-03 23:18
issue fixed

**Comment by tjdavis3** [comment] 2017-05-11 19:59
This error currently exists again in 6.0.0-rc1:

$ java -jar schemaspy-6.0.0-rc1.jar
May 11, 2017 12:20:19 PM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4edde6e5: startup date [Thu May 11 12:20:19 MDT 2017]; root of context hierarchy
Using database properties:
  [schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/pgsql.properties
Gathering schema details................................................(192sec)
Connecting relationships................................................(2sec)
Writing/graphing summary..12:23:35.007 WARNING: Main.main - Bad config Unable to find requested file: file:/Users/.../schemaspy-6.0.0-rc1.jar!/layout/schemaSpy.css

**Comment by Riggs333** [comment] 2017-05-11 20:23
This issues has the same root cause as #83

I'll try to provide a fix tommorrow as long as noone else does until then.

**Comment by rafalkasa** [comment] 2017-05-12 05:55
@Riggs333 now I remember why this isJarFile method was added to the Config class.

You can understand more when you will analyzing my commit  71e32e7 which is fixing the problem reported once again by @tjdavis3.

**Comment by rafalkasa** [comment] 2017-05-12 06:14
@tjdavis3 I try to reproduce the issue and after few tests I can't.
I verify schemaspy lunched it from InteliJ IDEA, from command shell and still everything is working correctly.

Your schemaspy-6.0.0-rc1.jar is build by you on your local machine or maybe downloaded version from [schemaspy 6.0.0-rc1](https://github.com/schemaspy/schemaspy/releases/download/v6.0.0-rc1/schemaspy-6.0.0-rc1.jar)

Third version can be [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar)

Could you tell as which version did you use ?

**Comment by rafalkasa** [comment] 2017-05-12 06:17
@Riggs333 you prepare the fix how did you reproduce the issue ? This is strange thing unfortunately I try but I can't :-(

**Comment by Riggs333** [comment] 2017-05-12 06:19
I could not reproduced the issue as well as you, but found out that the css parameter was not used correctly.

**Comment by Riggs333** [comment] 2017-05-12 06:20
Thinking of it again I should have raised a separate issue. But this is strongly related.

**Comment by rafalkasa** [comment] 2017-05-12 06:26
Thank you for let me know, it was strange for me. Good that you also could not reproduce the issue.

From my point of view `-css`  parameter is different story but somehow related.

**Comment by tjdavis3** [comment] 2017-05-12 07:23
It was downloaded from the site

**Comment by rafalkasa** [comment] 2017-05-15 20:12
@Riggs333 I would like confirm the issue reported by @tjdavis3 if you download [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar) application throw exception described by @tjdavis3 only when you will run it from command line java -jar schemaspy-6.0.0-rc1.jar. I can't reproduce the issue before because I had in my configuration custom template provided `-template`.

**Comment by rafalkasa** [comment] 2017-05-17 12:45
@Riggs333 after few test I can't to reproduce this scenario based on changes made in pull request #87 but this must be verified also after the merge with master.

**Comment by Riggs333** [comment] 2017-05-18 05:37
I cannot reproduce the issue either. Nevertheless #90 should be merged to fix the other problem.
I would like to take a deeper look at this issue again if #90 and #87 are merged.

**Comment by tjdavis3** [comment] 2017-05-18 13:20
For what it's worth, after reading Rafal's email on the 15th, I extracted
the jar file contents and ran it as java -jar schemaspy-6.0.0-rc1.jar
-template schemaspy/layout and it worked.  It only failed when run without
-template (I had also previously tried running it from the extracted jar as
java org.schemaspy.Main, which also failed).

**Comment by rafalkasa** [comment] 2017-08-07 21:03
@tjdavis3 after many test I can't reproduce your scenario based on [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar). In my opinion problem was fixed and I'm close the issue.

**Closed by rafalkasa** 2017-08-07 21:03 UTC
Labels: bug, important

**Comment by jawadhk** [comment] 2017-08-22 09:32
I am sable to reproduce this issue

> Using database properties:
  [lib\schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/mysql.properties
Gathering schema details.........................................(0sec)
Connecting relationships.........................................(0sec)
Writing/graphing summary..14:29:21.006 WARNING: Main.main - Bad config Unable to find requested file: file:\C:\Users\Jawad\Desktop\HotelKey\SchemaSpy%20v6\lib\schemaspy-6.0.0-rc1.jar!\layout\lib\schemaSpy.css
E=1I=1
