### ISSUE TITLE
Docker image unavailable

### ISSUE THREAD

**Issue by pomverte** [schemaspy/schemaspy#350] opened 2018-06-11 15:25 UTC
I'm trying to pull the lastest stable release of this image.
Reference : https://hub.docker.com/r/schemaspy/schemaspy/

## Expected Behavior
Pulling `schemaspy/schemaspy` with tag `6.0.0-rc2` should give me the docker image of schemaspy with the release `6.0.0-rc2`

## Current Behavior
Only `schemaspy/schemaspy:snapshot` is available

## Steps to Reproduce (for bugs)

1. Pulling default tag `latest`
```
[root@uberserver]# docker pull schemaspy/schemaspy
Using default tag: latest
Trying to pull repository docker.io/schemaspy/schemaspy ...
Pulling repository docker.io/schemaspy/schemaspy
Tag latest not found in repository docker.io/schemaspy/schemaspy
```

2. Trying to pull release `6.0.x`
```
[root@uberserver]# docker pull schemaspy/schemaspy:6.0.0-rc2
Trying to pull repository docker.io/schemaspy/schemaspy ...
Pulling repository docker.io/schemaspy/schemaspy
Tag 6.0.0-rc2 not found in repository docker.io/schemaspy/schemaspy
[root@uberserver]# docker pull schemaspy/schemaspy:v6.0.0-rc2
Trying to pull repository docker.io/schemaspy/schemaspy ...
Pulling repository docker.io/schemaspy/schemaspy
Tag v6.0.0-rc2 not found in repository docker.io/schemaspy/schemaspy
[root@uberserver]# docker pull schemaspy/schemaspy:6.0
Trying to pull repository docker.io/schemaspy/schemaspy ...
Pulling repository docker.io/schemaspy/schemaspy
Tag 6.0 not found in repository docker.io/schemaspy/schemaspy
```

3. Pulling `snapshot`
```
[root@uberserver]# docker pull schemaspy/schemaspy:snapshot
Trying to pull repository docker.io/schemaspy/schemaspy ...
snapshot: Pulling from docker.io/schemaspy/schemaspy

Digest: sha256:1107f029df1422a7c0cc4f4734a128c88aebf3b2501e11912cc745f41f25b1d2
```

## Your Environment

* CentOs 7.3 : `3.10.0-514.16.1.el7.x86_64`
* Docker : `Docker version 1.12.6, build 3a094bd/1.12.6`

**Comment by npetzall** [comment] 2018-06-11 16:06
This is pretty much duplicate of #239.

Latest will be available when proper release has been done. 
Docker was added after rc(s) where created.

@rafalkasa if we want we can add the old releases I think I can do it manually.
I could add all rc and point latest towards rc2 if rc are to be considered stable. 
We could do it just for now and later only set latest for proper releases. 

Scenario would be 6.0.0 has been released so it's latest we do rc1 for 7.0.0 what should be latest.

**Comment by pomverte** [comment] 2018-06-11 16:20
This is indeed a duplicate !
Thank you for your reply

**Comment by npetzall** [comment] 2018-06-11 16:26
However we hope to do a 6.0.0 release soon, and I truly hope that the testing we have added more or less make the snapshot usable.

**Comment by npetzall** [comment] 2018-08-05 21:32
6.0.0 has been release and `docker pull schemaspy/schemaspy ` now works

**Closed by npetzall** 2018-08-05 21:33 UTC
