### ISSUE TITLE
Failed to determine auto increment status when database has spaces in name

### ISSUE THREAD

**Issue by bvukas** [schemaspy/schemaspy#134] opened 2017-08-16 14:37 UTC
In MySQL I have database named `Test 1.0` and table named `Table 1.0`. 

This is log output:

Aug 16, 2017 4:29:53 PM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@30dae81: startup date [Wed Aug 16 16:29:53 CEST 2017]; root of context hierarchy
Aug 16, 2017 4:29:53 PM org.schemaspy.Config loadProperties
INFO: Configuration file not found
Using database properties:
  [schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/mysql.properties
Gathering schema details...16:29:55.162 WARNING: TableService.initColumnAutoUpdate - Failed to determine auto increment status: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1.0.`Table 1.0` where 0 = 1' at line 1
16:29:55.163 WARNING: TableService.initColumnAutoUpdate - SQL: select * from Test 1.0.`Table 1.0` where 0 = 1
.(0sec)
Connecting relationships....(0sec)
Writing/graphing summary..........(0sec)
Writing/diagramming details.Table -> Table 1.0
(0sec)
Wrote relationship details of 1 tables/views to directory './Test10' in 2 seconds.
View the results by opening ./Test10/index.html

As result, id column in Table 1.0 is not marked as auto incremented

**Comment by npetzall** [comment] 2017-08-16 19:15
Do you get correct output except the auto increment on id column.

**Comment by bvukas** [comment] 2017-08-17 18:16
Honestly, I did not check everything else, but I did not notice that anything else was broken.

**Comment by npetzall** [comment] 2017-08-17 18:21
I just asked since I wanted to scope down the issue. To possibly one method.

But if it's just a db called "Test 1.0", a table called "Test 1.0" and a Pk column id with autoincrement it shouldn't be that hard to reproduce.

**Comment by rafalkasa** [comment] 2017-08-17 19:20
This issue is quite interesting I don't imagine before that somebody can have table or database with space in the name. Thank you @bvukas for report the issue.

**Comment by bvukas** [comment] 2017-08-18 07:54
Script to create database and table that can be used to reproduce issue:

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 DROP DATABASE IF EXISTS `Test 1.0`*/;

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `Test 1.0` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `Test 1.0`;
DROP TABLE IF EXISTS `Table 1.0`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Table 1.0` (
  `id` int(11) NOT NULL,
  `col1` varchar(45) DEFAULT NULL,
  `col2` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `Table 1.0` WRITE;
/*!40000 ALTER TABLE `Table 1.0` DISABLE KEYS */;
INSERT INTO `Table 1.0` VALUES (1,'a',1),(2,'b',2);
/*!40000 ALTER TABLE `Table 1.0` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

**Comment by npetzall** [comment] 2017-11-03 13:52
@bvukas 
Isn't your script missing the AUTO_INCREMENT instruction.
```
CREATE TABLE Table 1.0 (
id int(11) NOT NULL AUTO_INCREMENT,
col1 varchar(45) DEFAULT NULL,
col2 int(11) DEFAULT NULL,
PRIMARY KEY (id)
);
```

Then again, it's not the only problem. I'm working on fixing this. We have lots of places we do queries that aren't quoted. Which produces problem with both Tables with spaces and databases/schemas with spaces.

**Comment by bvukas** [comment] 2017-11-15 07:30
@npetzall no, it is not missing instructions: https://dev.mysql.com/doc/refman/5.7/en/example-auto-increment.html

**Comment by npetzall** [comment] 2017-11-15 08:22
I'm sorry I assumed that the supplied schema would have auto_increment but for the issue it doesn't matter the root cause is the unquoted queries the application did. So this should be fixed  in my pull request. Waiting for approval and merge.

**Closed** 2017-11-29 00:15 UTC
Labels: enhancement, needs investigation

**Comment by npetzall** [comment] 2017-12-16 11:34
It does support spaces. The issue with the example is dots in table name and it's a mysql-connector-java issue.
