### ISSUE TITLE
SchemaMeta - Remote relationship

### ISSUE THREAD

**Issue by gary208** [schemaspy/schemaspy#548] opened 2019-04-22 20:55 UTC
## Question
Is there a way to define a relationship in SchemaMeta to a table in another schema?  I looked at https://schemaspy.readthedocs.io/en/latest/configuration/schemaMeta.html#add-relationships and tried remoteSchema but I always get the warning:
` Undefined column 'XX.XX' referenced by 'XX.XX' in XML metadata`

I am using PostgreSQL version 8.3.23 and have tried both SchemaSpy versions 6.1.0 and 6.0.0

Thanks

**Comment by npetzall** [comment] 2019-04-22 21:54
Just so that I know if this might be a bug or not.

When defining the relationship did you use `remoteCatalog` and `remoteSchema` attributes?

I'm a bit unsure if you also need to define the remote table.
https://schemaspy.readthedocs.io/en/latest/configuration/schemaMeta.html#add-remote-tables

I'm in the middle of bug fix, but I'll try to recreate the the scenario and add it to documentation.

**Comment by gary208** [comment] 2019-04-22 22:31
Yes I tried with both options and also with just remoteSchema.  Not sure if it's a bug or not.  Thanks for the quick reply!


-------- Original message --------

**Comment by npetzall** [comment] 2019-04-25 00:44
Sorry for the wait, I stumble upon some issues with the bug I was fixing.

I think I'll classify this as a bug or can be improved.

As an example
```xml
<table name="releases" remoteCatalog="newsletters" remoteSchema="newsletters"> <!-- remote table needs to be addded --> 
  <column name="email"/> <!-- referenced column needs to be added to the table -->
</table>
<table name="user"> <!-- Exists in the schema analyzed -->
  <column name="email">
    <foreignKey table="releases" column="email" remoteCatalog="newsletters" remoteSchema="newsletters" />
  </column>
</table>
```

I'll mark this as an enhancement, since the remote table is created, but not the column.
So I think we should add the column if missing. Which would reduce it to.
```xml
<table name="user"> <!-- Exists in the schema analyzed -->
  <column name="email">
    <foreignKey table="releases" column="email" remoteCatalog="newsletters" remoteSchema="newsletters" />
  </column>
</table>
```

No need to create the remote table and column.

**Comment by npetzall** [comment] 2019-04-25 20:29
Duplicate of #525

**Closed** 2019-04-26 04:48 UTC
Labels: bug, enhancement, question
