### ISSUE TITLE
SchemaSpy won't show PostgreSQL functions in "routines"

### ISSUE THREAD

**Issue by telmotrooper** [schemaspy/schemaspy#560] opened 2019-05-28 16:15 UTC
## Expected Behavior

When generating documentation for PostgreSQL databases functions and their triggers should show up in the "routines" page of the documentation. 

## Current Behavior

PostgreSQL functions and their triggers are ignored by SchemaSpy.

## Steps to Reproduce (for bugs)

1. Create a function and a trigger in your PostgreSQL database, like:
```
-- When a new markup is added, add an end date to the previous one
CREATE OR REPLACE FUNCTION expire_old_markup() 
RETURNS TRIGGER AS 
$insert_markup$
BEGIN
  UPDATE markups SET end_date = new.start_date
  WHERE end_date IS NULL AND id != new.id;
  RETURN NULL;
END;
$insert_markup$
LANGUAGE plpgsql;

CREATE TRIGGER expire_old_markup AFTER
INSERT ON markups
FOR EACH ROW
EXECUTE PROCEDURE expire_old_markup();
```
2. Generate documentation for your database with SchemaSpy;
3. Click "routines" and notice how the added function does not show.

## Context

* Database type: PostgreSQL 11.2
* Database driver version: JDBC 42.2.5
* Full command including arguments how you run SchemaSpy: `java -jar schemaspy-6.0.0.jar -t pgsql -dp postgresql-42.2.5.jar -db mydb -host localhost -port 5432 -s public -u postgres -o docs`

## Your Environment

* Version used: 6.0.0
* Environment name and version: Firefox 67.0
* Operating System and version: Arch Linux
* Java version: 8.u212

**Comment by npetzall** [comment] 2019-05-28 16:40
#444 #470 I'm gonna lookup the trigger issue I believe we have one for triggers.

As for routines use the snapshot or copy the pgsql databaseType from github and use it. 

Same folder as schemaspy.jar and use `-t pgsql11` instead of `-t pgsql`

**Comment by npetzall** [comment] 2019-05-28 16:41
#440 for triggers.

Closing as partially solved and duplicate of #440

**Comment by telmotrooper** [comment] 2019-05-28 17:02
@npetzall Thank you. I downloaded the [snapshot for 6.1.0](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.0-SNAPSHOT.jar) from the section Latest Build in the README, executed it with `-t pgsql11` as suggested and can confirm the functions now show in the documentation.

**Closed** 2019-05-28 17:03 UTC

**Comment by npetzall** [comment] 2019-05-28 17:13
There's also #460 which we probably should revive. Then it should be a matter of figuring out a sql query for pgsql to get triggers.
