### ISSUE TITLE
MacOSX El Capitan renderer bug

### ISSUE THREAD

**Issue by mlg-aabouzahr** [schemaspy/schemaspy#132] opened 2017-08-08 12:04 UTC
Hey, this si my first time using schemaSpy on MacOSX.  When i run the following schemaspy command:

`java -jar schemaSpy_5.0.0.jar -t mysql -o ./07072017 -host 127.0.0.1 -db test -s mysql -u root -dp java-mysql/mysql-connector-java-5.1.43/mysql-connector-java-5.1.43-bin.jar -hq`

It gives me a seemingly non-helpful Java runtime error:

[schemaSpy_5.0.0.jar]/net/sourceforge/schemaspy/dbTypes/mysql.properties
Gathering schema details...java.lang.NullPointerException
	at net.sourceforge.schemaspy.model.Table.initColumnAutoUpdate(Table.java:338)
	at net.sourceforge.schemaspy.model.Table.initColumns(Table.java:303)
	at net.sourceforge.schemaspy.model.Table.<init>(Table.java:88)
	at net.sourceforge.schemaspy.model.Database$TableCreator.createImpl(Database.java:1003)
	at net.sourceforge.schemaspy.model.Database$TableCreator.create(Database.java:999)
	at net.sourceforge.schemaspy.model.Database.initTables(Database.java:250)
	at net.sourceforge.schemaspy.model.Database.<init>(Database.java:71)
	at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:211)
	at net.sourceforge.schemaspy.Main.main(Main.java:42)

Adding the `-all` flag seems to circumvent this error but it starts to give me another graphiz-related error:

`net.sourceforge.schemaspy.util.Dot$DotFailure: 'dot -T.png ./07072017/root/diagrams/games.1degree.dot -o./07072017/root/diagrams/games.1degree.png -Tcmapx' failed with return code 1`

Now, I see a similar if not identical issue was reported here https://github.com/schemaspy/schemaspy/issues/33

However i don't see how I can use the `-renderer :quartz` flag anywhere.  Adding it to the schemaspy command doesn't have much of an effect.

Thank you very much

**Comment by npetzall** [comment] 2017-08-08 12:08
Use `-renderer :quartz`

For details check #33

**Comment by mlg-aabouzahr** [comment] 2017-08-08 13:40
@npetzall Yea, but how do I use it?  Do I tack that onto my usual schemaspy command?  That doesn't seem to fix the dot-related problems..

**Comment by npetzall** [comment] 2017-08-08 13:51
Sorry, I jumped the gun. -s argument should be same as -db for mysql.

So `-s test` as -db is is test.

**Comment by npetzall** [comment] 2017-08-08 13:52
Also you are using 5.0.0 which is well deprecated use the 6.0.0-rc1

**Comment by mlg-aabouzahr** [comment] 2017-08-08 14:09
@npetzall Ah thanks for the heads up about 6.0.0.  Looks so much better.  But the problem still persists.  I get similar errors and the Relationships file is missing or blank even with the above `-renderer` flag.

I am running `dot - graphviz version 2.40.1 (20161225.0304)`

My command currently looks like:
`java -jar schemaspy-6.0.0-rc1.jar -t mysql -o ./08072017 -host 127.0.0.1 -s test -db test -u root -dp java-mysql/mysql-connector-java-5.1.43/mysql-connector-java-5.1.43-bin.jar -gv /usr/local/Cellar/graphviz/2.40.1/ -hq -renderer :quartz`

**Comment by npetzall** [comment] 2017-08-08 14:57
Is the Xml file empty as well? 

Could you test with the snapshot version [snapshot](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar) and supply a new stacktrace.

Could you supply a script to create tables in the testdatabase?

**Comment by mlg-aabouzahr** [comment] 2017-08-08 15:15
@npetzall 
Using 6.0.0.1 I get this:
```
INFO  - Starting Main v6.0.0-rc1 on mlgtemp3s-mbp.activision.com with PID 5041 (/Users/aabouzahr/tools/schemaspy-6.0.0-rc1.jar started by aabouzahr in /Users/aabouzahr/tools)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Failed to validate png renderer ':cairo'.  Reverting to default renderer for png.
INFO  - Failed to validate png renderer ':gd'.  Reverting to default renderer for png.
INFO  - Failed to validate png renderer ':quartz'.  Reverting to default renderer for png.
INFO  - renderer ':quartz' is not supported by your graphvizVersion of dot
INFO  - Using database properties:
INFO  -   [schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/mysql.properties
INFO  - Connected to MySQL - 5.5.54
INFO  - Gathering schema details
Gathering schema details................(0sec)
Connecting relationships................(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
..../usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng ./08072017/diagrams/summary/relationships.real.compact.dot -o./08072017/diagrams/summary/relationships.real.compact.png -Tcmapx: Format: "png" not recognized. Use one of:
org.schemaspy.util.Dot$DotFailure: '/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng ./08072017/diagrams/summary/relationships.real.compact.dot -o./08072017/diagrams/summary/relationships.real.compact.png -Tcmapx' failed with return code 1
......(3sec)

```

It then proceeds to show the dot-related failure that have been showing up before.

**Comment by npetzall** [comment] 2017-08-08 15:50
Now it sounds like a compatability issue with graphviz.

We have docker image, else you might need to see if you can install an older version of graphviz. 

I'm saying this cause I might not have time to look at it tonight.
But I'll try.

**Comment by mlg-aabouzahr** [comment] 2017-08-08 15:57
@npetzall Thank you greatly for your help.  I used Graphviz v `2.36.0 (20140111.2315)` and it rendered just right.  Feel free to close this issue.

**Comment by rafalkasa** [comment] 2017-08-08 20:43
@npetzall I believe that case that had @mlg-aabouzahr is good for prepare the documentation because time to time we have OSX users that have the same issue. I don't want to close this issue as long as we will not prepare documentation.

**Comment by 5hel2l2y** [comment] 2017-08-24 17:18
Thanks for keeping this thread active!!

I too ran into the same issue on Mac with PostgresSQL 
`Writing/diagramming details.net.sourceforge.schemaspy.util.Dot$DotFailure: 'dot -Tpng:gd  <file-path>.dot <file-path>.png -Tcmapx' failed with return code 139`.

The website provided the 5.0.0 version, even though I had Graphviz 2.40.1 from Homebrew.  The generated output had error message
> SchemaSpy was unable to generate a diagram of table relationships. 
SchemaSpy requires Graphviz version 2.2.1 or versions greater than 2.4 from www.graphviz.org.

The `-renderer :quartz` solution works for me, here's my command,
`sudo java -jar schemaspy-6.0.0-rc1.jar -t pgsql -host <host> -db <database> -s <schema> -u <user> -p <password> -o <output-path> -dp postgresql-42.1.4.jar -hq -renderer :quartz`

MacOS 10.12.6
PostgreSQL 9.6.4
Graphviz 2.40.1
SchemaSpy 6.0.0 RC1

**Comment by EriksOcakovskis** [comment] 2017-12-14 18:18
```-renderer :quartz``` did not work with Graphviz v2.40.1, downgrading to Graphviz v2.36 solved this issue for me.

MacOS 10.13.2
PostgreSQL 9.3.1.0
SchemaSpy 6.0.0 RC2

**Comment by evaneus** [comment] 2018-02-07 17:40
`-renderer :quartz` does not work for me, and I can't seem to locate Graphviz v2.36

**Comment by EriksOcakovskis** [comment] 2018-02-07 21:07
@evaneus if I remeber correctly, I got it [here](https://github.com/cannin/biopaxTutorial/blob/master/biopaxTutorial/software/graphviz-2.36.0.pkg)

**Comment by npetzall** [comment] 2018-04-09 20:11
@hauntingEcho Might wanna track this issue: https://github.com/ellson/MOTHBALLED-graphviz/issues/1287
It has the same return code as you get: 134, the previous return codes in this issue are 1 and 139.

Little more digging and the issue might be lost between github and gitlab.....

But basically it can be an issue with the information that we have written in the user.1degree.dot file.
Could you run this simple dot-file and see if it works:

```
digraph G {
  node [style=filled]
  abc [color=green]
  def [color="0.2,0.8,0.8"]
  ghi [color="#FF0000"]
  kl [color="#FF00007F"]
  mno [color=yellow, fontcolor="#FF00007F"]
  pqr [label=mno, color=yellow, fontcolor="#FF0000"]
  abc -> def [color="red:blue:#00FF00"]
}
```
Just to validate the graphviz installation.

**Comment by hauntingEcho** [comment] 2018-04-09 20:30
thanks!  I think you're right.  [This](https://gitlab.com/graphviz/graphviz/issues/1320) is the closest related bug I've found on gitlab.  I'll duplicate this info there when I get a chance tonight

**Comment by Vadorequest** [comment] 2018-04-17 11:12
Running into the same issue with MacOSX 10.13.3 (HSierra)

```
java -jar ~/bin/schemaspy-6.0.0-rc2.jar -t pgsql -db db_development -host localhost -u db -p db -o ./documentation/schemaspy -dp ~/bin/postgresql-42.2.2.jar -s public -noads -gv /usr/local/Cellar/graphviz/2.40.1/ -renderer :quartz
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on Ambroises-MacBook-Pro.local with PID 24430 (/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar started by vadorequest in /Users/vadorequest/dev/studylink)
INFO  - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar!/BOOT-INF/lib/spring-core-4.3.11.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Failed to validate png renderer ':cairo'.  Reverting to default renderer for png.
INFO  - Using database properties:
INFO  -   [/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/pgsql.properties
INFO  - Connected to PostgreSQL - 9.6.6
INFO  - Gathering schema details
Gathering schema details.....................................................(1sec)
Connecting relationships.....................................................(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
..../usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx: *** First throw call stack:
```

**Comment by npetzall** [comment] 2018-04-17 11:29
@Vadorequest 
Could you give some info about jvm. Version and vendor? For the reflective error. 
Could you supply the rest of the output, call stack for dot and the return/error code?
And finally did you download from the latest/snapshot link in reademe/overview or from the release page?

**Comment by Vadorequest** [comment] 2018-04-17 11:50
I downloaded the 5.0.0 jar version at https://sourceforge.net/projects/schemaspy/files/schemaspy/

I downloaded the 6.0.0-rc2 jar version on github (this repo) at https://github.com/schemaspy/schemaspy#schemaspy-v600-rc2
 
---
Java:

```
java --version
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

---

JRE:

```
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

---
Here is the output when using 5.0.0:

```
java -jar ~/bin/schemaSpy_5.0.0.jar -t pgsql -db db_development -host localhost -u db -p db -o ./documentation/schemaspy -dp ~/bin/postgresql-42.2.2.jar -s public -noads -gv /usr/local/Cellar/graphviz/2.40.1/ -renderer :quartz
Using database properties:
  [/Users/vadorequest/bin/schemaSpy_5.0.0.jar]/net/sourceforge/schemaspy/dbTypes/pgsql.properties
Gathering schema details.....................................................(3sec)
Writing/graphing summary............(9sec)
Writing/diagramming details..................................................(40sec)
Wrote relationship details of 50 tables/views to directory './documentation/schemaspy' in 54 seconds.
View the results by opening ./documentation/schemaspy/index.html
```

---
Here is the output when using 6.0.0-rc2:

<details>

```
SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on Ambroises-MacBook-Pro.local with PID 81152 (/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar started by vadorequest in /Users/vadorequest/dev/studylink)
INFO  - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar!/BOOT-INF/lib/spring-core-4.3.11.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Using database properties:
INFO  -   [/Users/vadorequest/bin/schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/pgsql.properties
INFO  - Connected to PostgreSQL - 9.6.6
INFO  - Gathering schema details
Gathering schema details.....................................................(1sec)
Connecting relationships.....................................................(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
..../usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx: *** First throw call stack:
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx: (
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    0   CoreFoundation                      0x00007fff3113efcb __exceptionPreprocess + 171
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    1   libobjc.A.dylib                     0x00007fff57de0c76 objc_exception_throw + 48
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    2   CoreFoundation                      0x00007fff311d7964 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    3   CoreFoundation                      0x00007fff310b5610 ___forwarding___ + 1456
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    4   CoreFoundation                      0x00007fff310b4fd8 _CF_forwarding_prep_0 + 120
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    5   CoreFoundation                      0x00007fff31052b34 CFStringCompareWithOptionsAndLocale + 68
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    6   ImageIO                             0x00007fff33995ad0 _ZN17IIO_ReaderHandler15readerForUTTypeEPK10__CFString + 52
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    7   ImageIO                             0x00007fff33969c94 _ZN14IIOImageSource14doBindToReaderEv + 434
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    8   ImageIO                             0x00007fff3396a30d _ZN14IIOImageSource18createImageAtIndexEmP13IIODictionary + 39
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    9   ImageIO                             0x00007fff3395806b CGImageSourceCreateImageAtIndex + 237
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    10  libgvplugin_quartz.6.dylib          0x0000000102a52b8f quartz_loadimage_quartz + 240
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    11  libgvc.6.dylib                      0x0000000102416305 gvloadimage + 265
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    12  libgvc.6.dylib                      0x0000000102415354 gvrender_usershape + 1127
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    13  libgvc.6.dylib                      0x000000010242c02a emit_html_tbl + 1298
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    14  libgvc.6.dylib                      0x000000010242bf98 emit_html_tbl + 1152
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    15  libgvc.6.dylib                      0x000000010242bab4 emit_html_label + 520
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    16  libgvc.6.dylib                      0x000000010243930e emit_label + 57
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    17  libgvc.6.dylib                      0x0000000102442f7b poly_gencode + 2018
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    18  libgvc.6.dylib                      0x000000010244f7af emit_node + 1025
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    19  libgvc.6.dylib                      0x000000010244e483 emit_graph + 4770
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    20  libgvc.6.dylib                      0x00000001024539ed gvRenderJobs + 5259
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    21  dot                                 0x0000000102407d62 main + 700
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx:    22  libdyld.dylib                       0x00007fff589d0115 start + 1
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx: )
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx: libc++abi.dylib: terminating with uncaught exception of type NSException
org.schemaspy.util.Dot$DotFailure: '/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx' failed with return code 134
Wrote relationship details of 50 tables/views to directory './documentation/schemaspy' in 25 seconds.
View the results by opening ./documentation/schemaspy/index.html
INFO  - Wrote table details in 19 seconds
INFO  - Wrote relationship details of 50 tables/views to directory './documentation/schemaspy' in 25 seconds.
INFO  - View the results by opening ./documentation/schemaspy/index.html
INFO  - Started Main in 27.345 seconds (JVM running for 28.085)

```

I can't put the full stack, too big for github.

**Comment by npetzall** [comment] 2018-04-17 12:34
Warning regards to reflection probably has to do with Java 10. So that's just like they write in the output a Spring issue.

`org.schemaspy.util.Dot$DotFailure: '/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/summary/relationships.real.compact.dot -o./documentation/schemaspy/diagrams/summary/relationships.real.compact.png -Tcmapx' failed with return code 134`

Is the interesting part, your getting the same return code as @hauntingEcho which found this issue reported to graphviz https://gitlab.com/graphviz/graphviz/issues/1320

But it's interesting that it works with 5.0.0

Which causes me to suspect that the dot-file might be different between 5.x and our 6.x or that the command-line used to call the dot executable is different.

I'm currently busy with kids until tonight (6-7 hrs). I'll check if the dot-files created are different or if the command-line is different.

I just realized that I didn't ask hauntingEcho to test with latest/snapshot.
@Vadorequest could to try with snapshot/latest https://github.com/schemaspy/schemaspy#latest-build just to make sure it's not something thats fixed (don't believe anything has been done but I could be wrong)

**Comment by Vadorequest** [comment] 2018-04-17 13:46
@npetzall I just did and there is only one visible change between 6-rc2 and 6-latest, it prints a red `ERROR` when failing:

```
/usr/local/Cellar/graphviz/2.40.1/bin/dot -Tpng:quartz ./documentation/schemaspy/diagrams/utils_requete_http.1degree.dot -o./documentation/schemaspy/diagrams/utils_requete_http.1degree.png -Tcmapx: libc++abi.dylib: terminating with uncaught exception of type NSException
ERROR - There was an error writing a dot file
```

**Comment by npetzall** [comment] 2018-04-17 13:50
I'll have a look at it tonight. I'm gonna dust of my old mac book pro and see if I can upgrade to High Sierra.

**Comment by npetzall** [comment] 2018-04-17 19:36
I haven had the time to get my mac book pro up on sierra.

But I did a light digging.
The graphviz issue  -> https://gitlab.com/graphviz/graphviz/issues/1320
Is talking about images that are to be embedded in the diagram.

It turns out that images has been added for PK and FK so I believe that is the issue and the reason why 5.0 works and 6.0 doesn't.

As a simple test, open one of the dot files and remove the IMG tags and run the command again and see if it fails.
But then again it's sort of what they are saying in https://gitlab.com/graphviz/graphviz/issues/1320

**Comment by npetzall** [comment] 2018-04-17 19:40
Difference between 5.x and 6.x is that images has been added for PK and FK.
The issue over at graphviz is about images.

So I'm 99% confident that the issue is with Graphviz and not with SchemaSpy in this case: Return code 134.

But I'm waiting for my mac book pro to be updated to High Sierra. For a final confirmation.

**Comment by npetzall** [comment] 2018-04-17 20:41
Manually testing on Sierra before upgrade to High. Works without a hitch.
dot - graphviz version 2.40.1 (20161225.0304) built for Sierra, brew command from #33 
`dot -Tpng:quartz user.1degree.gv -o user.1degree.png -Tcmapx`

**Comment by Vadorequest** [comment] 2018-04-17 22:35
https://gitlab.com/graphviz/graphviz/issues/1320 return 500 internal error for me for some reason.

What do you advise for now? We can't remove the tag for every dot file. I'll stay on 5.0 until this issue is resolved I guess. Did you report the bug to graphviz?

Thanks for your fast feedback.

**Comment by npetzall** [comment] 2018-04-17 22:43
Link seems to be working for me right now.

When testing manally without SchemaSpy it seems that `-renderer :cairo` should work

**Comment by npetzall** [comment] 2018-04-17 23:15
@hauntingEcho @Vadorequest 
cairo is a dependency to pango make sure they are installed
`brew list` will show installed formulas.
I assume that graphviz needs to be installed with `brew install graphviz --with-pango` at least with that command pango and cairo are installed.
It also seems that the renderer `gd` is broken it was for me same as in mentioned in #33 
To force cairo use `-renderer :cairo`

**Comment by Vadorequest** [comment] 2018-04-18 17:45
Indeed! It worked :)

```
java -jar ~/bin/schemaspy-6.0.0-rc2.jar -t pgsql -db db_development -host localhost -u db -p db -o ./documentation/schemaspy -dp ~/bin/postgresql-42.2.2.jar -s public -noads -gv /usr/local/Cellar/graphviz/2.40.1/ -renderer :cairo
```

**Comment by npetzall** [comment] 2018-04-18 17:48
@Vadorequest phu, I like told everyone that it should :smile:

**Comment by hauntingEcho** [comment] 2018-04-18 22:01
`-renderer :cairo` solves the issue for me as well - thanks!
(using rc2 & graphviz 2.40.1 installed using `--with-pango`)

**Comment by npetzall** [comment] 2018-06-12 09:35
I'll do a write up about OSX and Graphviz and add it to ReadMe and to ReadTheDocs.
Any new issue with osx and graphviz will result in update of said write up so that issues can be closed.

**Closed** 2018-06-17 16:07 UTC
Labels: documentation, graphviz, help wanted, question

**Comment by immo-huneke-zuhlke** [comment] 2018-10-02 10:15
`brew reinstall graphviz --with-pango --with-librsvg` worked for me.

**Comment by sergyer** [comment] 2019-03-14 18:56
> Use `-renderer :quartz`
> 
> For details check #33

Worked for me with  SchemaSpy version 5.0.0

**Comment by greyvugrin** [comment] 2022-01-11 20:36
Installing graphviz with brew now (as of 2021) installs both librsvg and pango by default. No need to pass the `--with-*` options: they are not valid anymore either, as others have commented.

`brew install graphviz` works fine using Cataline (10.15.7)
