### ISSUE TITLE
Support for Amazon Redshift database

### ISSUE THREAD

**Issue by thebogusman** [schemaspy/schemaspy#58] opened 2017-04-04 13:01 UTC
Redshift is compatible to some extent with postgres driver, unfortunately at some point, schemaspy throws the following exception:

```
Connecting relationships....14:57:15.152 SEVERE:  Main.main - Unable to determine a value for MaxIndexKeys due to missing system catalog data.
org.postgresql.util.PSQLException: Unable to determine a value for MaxIndexKeys due to missing system catalog data.
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getMaxIndexKeys(AbstractJdbc2DatabaseMetaData.java:64)
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getImportedExportedKeys(AbstractJdbc2DatabaseMetaData.java:3196)
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getImportedKeys(AbstractJdbc2DatabaseMetaData.java:3526)
        at org.schemaspy.service.TableService.connectForeignKeys(TableService.java:207)
        at org.schemaspy.service.DatabaseService.connectTables(DatabaseService.java:224)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:64)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:234)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
```

There is a dedicated JDBC driver for redshift (https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html), but it cannot be used in place of postgresql driver, due to different class naming.

**Comment by wkasa** [comment] 2017-04-13 20:13
Hi @thebogusman . I've created PR with support for redshift db. 
Please verify if everything works.

**Comment by rafalkasa** [comment] 2017-04-13 20:54
@thebogusman PR created by @wkasa was already merged. So you can clone the main repository for your test and verification.

**Comment by thebogusman** [comment] 2017-04-14 13:22
@wkasa thanks a lot! I really appreciate your effort.

I did some testing on a moderately large database. The first time it crashed with some NPE while loading/generating info for columns. So I deleted the output folder and run it once again with console output redirected to a file, but this time it finished successfully.

The end result is pretty much usable, but it has some issues:
1. Reported row count for some tables is -1 (affects about 10% of all tables, seems to be random)
2. I was generating docs for schema public, but there was also schema public_bkp present in the database at the time, with almost identical set of tables. This caused all the relations in the docs to be doubled, with one pointing to public.table and the other one to public_bkp.table. Tables from "public_bkp" schema are also present on the diagrams, but not on the table list.
3. Descriptions for columns are mixed up between different columns inside a table. This seems to be connected with the previous issue, as only the tables with lots of relations seems to be affected.

I'm attaching the command output, as there were some warnings/exceptions showing up along the way. I obfuscated the names of the tables, but hopefully they're not that important.

[output_obf.txt](https://github.com/schemaspy/schemaspy/files/922106/output_obf.txt)

**Comment by wkasa** [comment] 2017-04-14 15:02
@thebogusman any chance that you can prepare some test db? Or maybe script to create such database to reproduce this issue? I am not and redshift expert and I've only created simple test db to fix exception with connecting to this db.

**Comment by thebogusman** [comment] 2017-04-14 19:22
@wkasa sure, I will come up with something next week.

**Comment by thebogusman** [comment] 2017-04-14 21:41
@wkasa actually, I've already got it. Here's the ddl for both schemas:
[schemaspy_test_ddl.zip](https://github.com/schemaspy/schemaspy/files/922997/schemaspy_test_ddl.zip)

**Comment by wkasa** [comment] 2017-04-15 06:46
@thebogusman thanks! I'll look on it next week.

**Comment by wkasa** [comment] 2017-04-23 20:31
@thebogusman 
I checked your script and it looks like the problem is deeper. Below is printscreen from SQL Workbench, I used the same jdbc driver like in schemaspy. As you can see even there those tables are somehow related.
![image](https://cloud.githubusercontent.com/assets/17494518/25317164/7fe5b934-2873-11e7-8791-e020762c6a90.png)

**Comment by rafalkasa** [comment] 2017-04-23 21:01
@thebogusman based on @wkasa explanation I suppose that's something incorrect in your database.
Could you verify and let us know ?

**Comment by wkasa** [comment] 2017-04-23 21:08
@rafalkasa it looks ok on the database - there is no relation between this tables. It looks like some bug in jdbc drivers or something like this.

**Comment by rafalkasa** [comment] 2017-04-23 21:26
@wkasa thanks for your detailed explanation so if this is something in jdbc driver it will be not simple to fix... Do you have any suggestions ?

**Comment by thebogusman** [comment] 2017-04-23 21:29
@wkasa you're probably right. I can observe the same problem in DBeaver. I'll post an issue on Amazon's forum regarding that problem.

Amazon provides this view for retreiving foreign keys:
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_constraint_dependency.sql
It works ok on the schemas I sent you.

**Comment by wkasa** [comment] 2017-04-23 21:34
Ok then, let's wait until @thebogusman will receive some feedback from Amazon.

**Comment by wkasa** [comment] 2017-05-17 21:27
@thebogusman any update?

**Comment by lovegis** [comment] 2017-06-16 12:47
@thebogusman - can you please post the URL of this issue on the Amazon forum?  There is great interest to have SchemaSpy work with Redshift and I'd like to add to the conversation.

**Comment by seanmuth** [comment] 2017-07-12 23:04
+1 for interest in this. 
can help with testing/investigation

**Comment by npetzall** [comment] 2017-07-13 14:38
@seanmuth

There is a dbtype for redshift that you can test a provide feedback for.

[redshift](
https://github.com/schemaspy/schemaspy/blob/master/src/main/resources/org/schemaspy/types/redshift.properties)

**Comment by seanmuth** [comment] 2017-07-13 19:58
@npetzall getting a failed to load driver error trying to run with the latest docker snapshot:

```
Failed to load driver 'com.amazon.redshift.jdbc42.Driver'
This entry doesn't point to a valid file/directory: [/Users/seanmuth/Documents/Redshift/RedshiftJDBC42-1.2.1.1001.jar]
```
chmod 777 to the jar file to make sure it's not a file permissions thing, no luck

**Comment by npetzall** [comment] 2017-07-13 20:02
@seanmuth redshift driver is not included with the docker image. You need to bind mount the driver using -v if that wasn't done.

If you provide the docker run command without user/pass I might be able to help you. Also OS I assume osx or Linux at least.

**Comment by npetzall** [comment] 2017-07-13 20:06
-v "path-to-folder-with-jar:/drivers" add before image

**Comment by seanmuth** [comment] 2017-07-13 20:11
Got it thanks @npetzall, I don't have a ton of experience with docker yet, my avatar definitely applies here :-P

**Comment by npetzall** [comment] 2017-07-13 20:16
@seanmuth the image and docker is pretty new so the docs hasn't been battle tested. I'll think of an update to improve the docs. I read it now and the -v is quite hidden.

**Comment by seanmuth** [comment] 2017-07-13 20:48
no worries, I can help with docs too if you need it.

got through connecting relationships, error'd here:
```
.ERROR - Application startup failed
java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libfontmanager.so: Error relocating /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libfontmanager.so: AWTFontDefaultChar: symbol not found
```

**Comment by npetzall** [comment] 2017-07-13 21:59
@seanmuth I've noticed some possible improvements and also that I didn't pin the version of the "parent image" so might be an update there that has broken the docker image.

I'll have a look when I get to a computer. Currently in a cabin on the countrysidr with only a cellphone.

If your able to run locally without docker (graphiz installed) you can download the [snapshot.jar](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar)

The error you get is probably related to fontconfig but there might be changes in newer jdk. So the setup I've doesnt work. I'll investigate and fix, but later...

**Comment by seanmuth** [comment] 2017-07-13 22:10
Cabin in the countryside sounds great! I'll mess around locally and see where I can get!

**Comment by npetzall** [comment] 2017-07-14 15:14
@seanmuth you can join our chat on [gitter](https://gitter.im/schemaspy/schemaspy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by lovegis** [comment] 2017-07-17 23:31
Initial results for Redshift look promising.  I need to work on adding all
my constraints that exist in my postgres DB to redshift.  I did have to
research and add this to my command line was this database enforces ssl:

-connprops "ssl\=true;sslfactory\=org.postgresql.ssl.NonValidatingFactory"

Will report back with any issues.

FWIW, the layout of v6 is very nice.  I was previously using v5.

Will report back,

Reily

**Comment by drorm** [comment] 2017-08-12 19:10
I just successfully created a schema for redshift.

Instructions in https://gist.github.com/drorm/14ca3ac50d90cada44fa1d8f0e121bd1

**Comment by npetzall** [comment] 2017-08-12 19:31
There is a link to download the latest snapshot in the readme.md so you can skip the download I hope.

**Comment by drorm** [comment] 2017-08-12 21:14
Updated the gist.

When I downloaded the snapshot it had the save version/file name as the version I downloaded earlier. Probably makes sense to have them have different versions names.

**Comment by npetzall** [comment] 2018-08-06 12:58
@drorm we have changed the name and also yesterday released 6.0.0.

I failed to ask back then, was the schema looking OK. Do we have any outstanding issues with redshirt?

**Comment by drorm** [comment] 2018-08-19 20:14
The schema looked fine

**Comment by npetzall** [comment] 2019-03-02 21:07
Closing this.

Create new issues if found.

**Closed by npetzall** 2019-03-02 21:07 UTC
Labels: enhancement, important, in progress, needs investigation
