### ISSUE TITLE
MySQL 5.6: using non-existent schema gives output instead of error

### ISSUE THREAD

**Issue by sampablokuper** [schemaspy/schemaspy#330] opened 2018-05-17 18:16 UTC
*N.B. Based on the discussion at #329, this issue **might** be a duplicate of #222. If it does end up being confirmed as a duplicate, then of course it should also be closed as a duplicate. Thanks for your understanding.*

In the following example, the MySQL instance contains more than one database. The `my_mysql_user` is able to access only the `my_mysql_db` database; the other databases are accessible to the MySQL root user.

The MySQL instance does not contain any instances of the text `foobarbaz`.

## Expected Behavior
I would expect this &hellip;

```
$ ssh -f -o ExitOnForwardFailure=yes -L 10000:localhost:3306 \
        -i ~/.ssh/id_rsa_passwordless@192.168.122.68 sleep 10 ; \
    java -jar schemaspy-6.0.0-rc2.jar -t mysql \
        -dp drivers/mysql-connector-java-8.0.11.jar \
        -db my_mysql_db -u my_mysql_user -p my_mysql_pwd \
        -host 127.0.0.01 -port 10000 \
        -s foobarbaz -o foobarbaz
```

&hellip; to fail with an error message saying "Schema foobarbaz not found", or suchlike.

## Current Behavior
Instead, &hellip;

```
$ ssh -f -o ExitOnForwardFailure=yes -L 10000:localhost:3306 \
        -i ~/.ssh/id_rsa_passwordless@192.168.122.68 sleep 10 ; \
    java -jar schemaspy-6.0.0-rc2.jar -t mysql \
        -dp drivers/mysql-connector-java-8.0.11.jar \
        -db my_mysql_db -u my_mysql_user -p my_mysql_pwd \
        -host 127.0.0.01 -port 10000 \
        -s foobarbaz -o foobarbaz
```

&hellip; yields output. The output contains text strings that feature the string `foobarbaz`:

```
ag foobarbaz foobarbaz/
foobarbaz/index.html:6:  <title>my_mysql_db.foobarbaz Database</title>
foobarbaz/index.html:48:          <a href="index.html" class="navbar-brand"><b>my_mysql_db.foobarbaz</b> Database</a>
foobarbaz/index.html:82:                                        <h4>SchemaSpy Analysis of my_mysql_db.foobarbaz</h4>
foobarbaz/index.html:89:        <a href="my_mysql_db.foobarbaz.xml" title="XML Representation">XML Representation</a></br>
foobarbaz/routines.html:8:   <br><b>my_mysql_db.foobarbaz contains 0 procedures and 0 functions:</b><br><div class='indent'></div>
[...]
```

## Steps to Reproduce (for bugs)
See above, for the closest thing to reproduction steps that I can currently offer.

## Context

* Database type (e.g. MySQL): Oracle MySQL Community Edition 5.6
* Database driver version (if you use a special one): mysql-connector-java-8.0.11.jar
* Your DDL (sample how to reproduce the issue): unsure what is being asked for here.
* Full command including arguments how you run SchemaSpy: see above.

## Your Environment

* Version used: v6.0.0-rc2
* Environment name and version (e.g. Chrome 39): Debian 9 "Stretch"
* Operating System and version (e.g. Windows 10): Debian 9 "Stretch"
* Java version: OpenJDK 1.8.0_171 (see details below).

```
$ java -showversion
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by npetzall** [comment] 2018-05-17 20:29
Possible duplicate of #222 will investigate.

**Comment by npetzall** [comment] 2018-05-23 09:01
Schema name can't be null is a constructor argument validation and has nothing to do with database interactions. Mysql effectively ignores Schema arguments when retrieving data from DatabaseMetaData.
I've ranted about this before but. Docs say Schema and Database is the same thing. Well that's not true in JDBC here Catalog and Database is the same thing and Schema doesn't exist. 
So to summerize Database = Catalog, Schema Alias for Database which is Catalog.

**Closed by npetzall** 2018-05-23 09:01 UTC
Labels: duplicate

**Comment by sampablokuper** [comment] 2018-05-23 19:36
@npetzall wrote:
> Schema name can't be null is a constructor argument validation and has nothing to do with database interactions.

Thanks, but this issue isn't about the "Schema name can't be null" error. Issue #329 is about that error. Perhaps you included the above remark in your comment here by mistake?

> Mysql effectively ignores Schema arguments when retrieving data from DatabaseMetaData.
I've ranted about this before but. Docs say Schema and Database is the same thing. Well that's not true in JDBC here Catalog and Database is the same thing and Schema doesn't exist.
So to summerize Database = Catalog, Schema Alias for Database which is Catalog.

Thanks, but this issue isn't about JDBC or MySQL or what they consider schemas to be. Instead, it's about SchemaSpy's `-s` or `--schema` parameter, and its failure to warn or error when a non-existent schema name is passed to it, w.r.t. a MySQL database.

AFAICT, either SchemaSpy's `-s` or `--schema` parameter is inadequately documented in this respect, or else has a bug in this respect, or both. (Alternatively, perhaps you are figuring that fixing #329 would obviate the first two of these three cases.)

### Case 1: --schema parameter is inadequately documented in this respect

Currently, https://schemaspy.readthedocs.io/en/latest/started.html says:

> [-s schema]
>     Database schema. This is optional if it’s the same as user or isn’t supported by your database. Use -noschema if your database thinks it supports schemas but doesn’t (e.g. older versions of Informix).

However, it is not apparent from that documentation which of the following possibilities is true:

1. SchemaSpy's `--noschema` option should be used with MySQL (just as it should be used, according to the above documentation, with "older versions of Informix");
1. SchemaSpy's `-s` or `--schema` parameter is supported for MySQL;
1. SchemaSpy's `-s` or `--schema` parameter is **not** supported for MySQL;
1. SchemaSpy's `-s` or `--schema` parameter is **not** supported for MySQL *but is required anyway*.

(The last of these four possibilities should not be possible, according to the documentation quoted above, but I have listed it here for reasons that will soon become clear.)

`java -jar schemaspy-6.0.0-rc2.jar -dbhelp` is supposed to provide instructions for connecting to databases, but it does not specify which of those three possibilities is true, either. Here is the help text it contains re: connecting to MySQL databases:

```
INFO  - Built-in database types and their required connection parameters:
[...]
mysql:
  MySQL
   -hostOptionalPort 
   -db          database name
```

and compare this to what the same command says about Informix:

```
 informix:
  InformixSQL
   -hostOptionalPort 
   -db          database name
   -server      database server
```

Note the lack of a `-s` or `--schema` parameter for both MySQL and Informix. This seems to narrow the possibilities down to any but the second option out of the four mentioned above.

Attempting to use `--noschema` fails (per #329), so that narrows things down to just the last two possibilities out of the four mentioned above.

Attempting to not use a schema also fails (per #329), so that narrows things down to just the last possibility out of the four mentioned above.

But surely, if a `-s` or `--schema` parameter is used, then it should at least be somehow *correct*. The documentation above just seems to imply that it should not be "the same as user", but this leaves undefined what the value *should* be, and also leaves undefined what is supposed to happen if an arbitrary value is used.

I think the documentation could be improved in this respect.

That being so, and unless case 3 below applies, this issue should probably be re-opened.

### Case 2: --schema parameter is buggy in this respect

It is already clear (from #329) that the `-s` or `--schema` parameter's implementation has bugs. But another bug, presumably, is that it should throw an error (or at least give a warning) if a value is used that does not correspond to *something* in the database.

What the possible *something*s should be - Catalog or Schema or Database or some conjunction of these - is a matter for SchemaSpy's developer/maintainer to decide. But regardless, if a user uses, for example, `-s foobarbaz` when connecting SchemaSpy to a database that contains no entity (or meta-entity) called "foobarbaz", then SchemaSpy should indeed (throw an error (or at least give a warning))[https://github.com/schemaspy/schemaspy/issues/330#issue-324131647]

That being so, and unless case 3 below applies, this issue should probably be re-opened.

### Case 3: fixing #329 obviates case 1 and/or case 2

If the idea behind closing this issue without a direct fix is that fixing #329 will effectively nullify this issue, then perhaps that is correct. If so, then I guess this issue should stay closed.

**Comment by npetzall** [comment] 2018-05-23 20:13
Depending on what you consider a warning/error.
Doing the same on SQLServer yields: (using a non-existing schema)

```
docker run -v "/home/nosse/.m2/repository/com/microsoft/sqlserver/mssql-jdbc/6.2.2.jre8/mssql-jdbc-6.2.2.jre8.jar:/drivers/mssql-jdbc-6.2.2.jre8.jar" -v "$PWD/arts_db_model_rw:/output" schemaspy/schemaspy:snapshot -t mssql08 -host 192.168.0.21 -port 1433 -u sa -p qwerty123! -db ODM -s hejsan      
Running Main-Class org.springframework.boot.loader.JarLauncher
With drivers:mssql-jdbc-6.2.2.jre8.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0-rc2 on 17781819fedc with PID 1 (/schemaspy-6.0.0-rc2.jar started by java in /)
INFO  - The following profiles are active: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Resolving dbType: mssql08 ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
INFO  - Connected to Microsoft SQL Server - 14.00.3025
INFO  - Gathering schema details
Gathering schema details...(0sec)
Connecting relationships...(0sec)
Writing/graphing summary.WARN  - No tables or views were found in schema 'hejsan'.
ERROR - The schema 'hejsan' could not be read/found, schema is specified using the -s option.Make sure user 'sa' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):
db_accessadmin
db_backupoperator
db_datareader
db_datawriter
db_ddladmin
db_denydatareader
db_denydatawriter
db_owner
db_securityadmin
dbo
guest
INFORMATION_SCHEMA
sys
ARTS_DICT
INFO  - Schemas with tables/views visible to 'ARTS_DICT
INFORMATION_SCHEMA
dbo
sys':
{}
WARN  - Empty schema
INFO  - Started Main in 2.235 seconds (JVM running for 2.63)
```
As for the comment about schema can't be null, was just in the context of mysql it doesn't have an effect. Since mysql doesn't have have schemas it has catalogs and catalog and database are the same.
The connection specifies a database which means you get a default catalog. All this is just JDBC implementation. In the actual query language and metadata present in the database (information_schema) schema does exist.

If #222 is fixed, you would get the "WARN - Empty schema" as I did in sql server case.
The faulty code first runs a query:
`select table_schema as table_catalog, null as table_schema, table_name, table_comment, table_rows from information_schema.tables where table_schema=:schema and table_type='BASE TABLE'`
But since the schema doesnt exist it get an empty result.
It then tries to use JDBC DatabaseMetaData.getTable() and due to mysql jdbc driver implementation everything goes bananas and it uses the default catalog and ignores the schema that you requested.

The JDBC DatabaseMetaData.getTable() should only be used if the custom query failes. If it succeeds with empty result, then empty result is the result.

I hope I don't make you cry or laugh but -noschema doesn't do anything.....no code is using that flag.
As for -s, -schemas, -schemata they probably exist for legacy reason.
There is no need for all three, and I'm actually looking into change how it all works.

I want `-cat` `-schema` to be used as narrowing/filtering. So that they arent required unless you want to extract a single catalog or a single schema. So in most cases they won't be used. This would eliminate the -all option that exists.

Other issues related to you latest comment.
#52 #254 #255
#117

**Comment by sampablokuper** [comment] 2018-05-23 23:37
Thanks for the clarifications :)

> If #222 is fixed, you would get the "WARN - Empty schema" as I did in sql server case.

Cool, good to know :)

> I hope I don't make you cry or laugh but -noschema doesn't do anything.....no code is using that flag.

That did make me chuckle; thanks :)

> As for -s, -schemas, -schemata they probably exist for legacy reason.
There is no need for all three, and I'm actually looking into change how it all works.
>
> I want -cat -schema to be used as narrowing/filtering. So that they arent required unless you want to extract a single catalog or a single schema. So in most cases they won't be used. This would eliminate the -all option that exists.

Also good to know. It's clear that you've been giving this some thought for some time and have a plan.

Your plan sounds good to me, and I wish you luck and good progress!

Thanks again :)
