### ISSUE TITLE
tables with same name in different schemas cannot coexist

### ISSUE THREAD

**Issue by hauntingEcho** [schemaspy/schemaspy#298] opened 2018-04-09 21:51 UTC
When attempting to use schemaspy with a user who has access to two schemas, one containing a table & the other containing a view with the same name as that table, both will be shown in `index.html` but both links will point to  `tables/${TABLENAME}.html`, which describes only one (or a mixture of both).

## Expected Behavior
- only the specified schema should be shown (see #299)
- if both schemas are specified, identically-named table-like entities across multiple schemas should not conflict

## Current Behavior
Both entities are shown in index.html but their file in the `tables` subdirectory conflicts.

- with the given DDL & command line, test2.a is described
- if test1 and test2 are swapped in the DDL, but the commandline is left alone, and additional table named `test_table_1` is included with columns id & name.  `test_table_1` is NOT generated for my existing view-only schema, so I don't think this is a general problem for schemas without true tables.
- if test1 & test2 are swapped in both the DDL & commandline, a table with the column `id2` (as in the view) will be listed for `a`, but no `create view` statement shown.

## Possible Solution
per-schema folder structure (`output/$SCHEMA/$TABLE`) or namespaced filename (`output/$SCHEMA.$TABLE`)

## Context
* Database type (e.g. MySQL): MySQL installed via homebrew.  `mysql --version` returns `mysql  Ver 14.14 Distrib 5.7.21, for osx10.13 (x86_64) using  EditLine wrapper`
* Database driver version (is you use a special one): see Docker image
* Your DDL (sample how to reproduce the issue):
```
create database test1;
create database test2;
create table test1.a(id1 int);
create view test2.a as select id1 as id2 from test1.a;
create user 'testUser'@'localhost' identified by 'password';
grant select, show view on test1.* to 'testUser'@'localhost';
grant select, show view on test2.* to 'testUser'@'localhost';
flush privileges
```

* Full command including arguments how you run SchemaSpy: `docker run -v /Users/matt.beary/Desktop/example:/output schemaspy/schemaspy:snapshot -db test1 -s test1 -u testUser -p password -t mysql -host docker.for.mac.localhost -port 3306`

## Your Environment
* Version used: see Docker image, seems to be last updated March 26
* Environment name and version (e.g. Chrome 39): `snapshot` docker image
* Operating System and version (e.g. Windows 10): OSX 10.13.4, Docker 18.03.0-ce-mac60 (23751)
* Java version: see Docker image

**Comment by hauntingEcho** [comment] 2018-04-10 15:11
thanks!
more info because I was curious:
when the view is in test1 & the command line is `docker run -v /Users/matt.beary/Desktop/example:/output schemaspy/schemaspy:snapshot -db test2 -all -u testUser -p password -t mysql -host docker.for.mac.localhost -port 3306`, it generates test1, test2, and information_schema.  Both test1 and test2 show both the table & view `a` in their contents, the details of both in test1 match the view definition, and both in test2 have only `id2` (which is the view's column name) and no view statement.  Oddly enough, `information_schema`'s result exactly matches the result for `test2`

**Comment by npetzall** [comment] 2018-04-10 15:20
There is an old issue regarding information_schema an tables from other schemas when using -all

There are two things to consider. 

One i the SQL overrides in https://github.com/schemaspy/schemaspy/blob/master/src/main/resources/org/schemaspy/types/mysql.properties second is mysql weird position on catalogs, schemas and databases. Sometimes database = schema and others catalog = database and they say schema and database is the same.

I'll have a look tonight (in 5-6 hrs).

**Comment by npetzall** [comment] 2018-04-10 19:26
Same issue as #222 

https://github.com/schemaspy/schemaspy/blob/a0d68ccba7bcc8970784898f887b2608d20666f6/src/main/java/org/schemaspy/service/DatabaseService.java#L426

So we use custom SQL query since mysql is strange. The schema test1 doesn't contain any views so (schemaspy fallsback to query DatabaseMetadata).

If you check 6.0 branch of mysql-connector-j which is on github and the getTables function:
https://github.com/mysql/mysql-connector-j/blob/3dab84f4d9bede3cdd14d57b99e9e98a02a5b97d/src/main/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L3830

I takes a schemaPattern argument but it's not used in the method.

If you later look at the returned resultSet:
https://github.com/mysql/mysql-connector-j/blob/3dab84f4d9bede3cdd14d57b99e9e98a02a5b97d/src/main/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L3942

You see that row, field 2 is always null (that's the schema field).
But field 1 catalog is populated.

This is might be my lack of mysql knowledge.
https://github.com/mysql/mysql-connector-j/blob/3dab84f4d9bede3cdd14d57b99e9e98a02a5b97d/src/main/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L3868

But on that line it seems as if catalog and schema might be the same thing.....

So this will be corrected with #222.
Or it would be corrected if mysql-connector-j wouldn't ignore schemaPattern.

**Comment by npetzall** [comment] 2018-04-12 19:42
duplicate #222

**Comment by npetzall** [comment] 2018-04-12 19:42
Duplicate of #222

**Comment by npetzall** [comment] 2018-05-31 18:55
This is really old, but #222 has been fixed and if duplicate is true this issue should now be resolved.
@hauntingEcho Can you verify that with a latest build this is resolved.

**Comment by hauntingEcho** [comment] 2018-05-31 20:06
this is working as expected now, when built from the master branch - thanks so much!

**Closed** 2018-05-31 20:08 UTC
Labels: duplicate
