### ISSUE TITLE
Multiple Schemas Broken on Embedded H2 DB

### ISSUE THREAD

**Issue by tresat** [schemaspy/schemaspy#388] opened 2018-07-30 02:03 UTC
## Expected Behavior
Using h2 version 1.4.196 I have an embedded db with 2 schemas.  I should be able to use the schemas option to generate diagrams for multiple schemas.

## Current Behavior
If I list either schema I'm interested in using the "schemaspy.s=schema1" option in the schemaspy.properties file, all is well.  If I switch to supplying "schemaspy.schemas=schema1,schema2" instead, changing nothing else, I get the following:

Failed to connect to database URL [jdbc:h2:C:/Projects/Test/testdb]

org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
        at org.h2.engine.Database.getPageStore(Database.java:2476)
        at org.h2.engine.Database.open(Database.java:697)
        at org.h2.engine.Database.openDatabase(Database.java:276)
        at org.h2.engine.Database.<init>(Database.java:270)
        at org.h2.engine.Engine.openSession(Engine.java:64)
        at org.h2.engine.Engine.openSession(Engine.java:176)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
        at org.h2.Driver.connect(Driver.java:69)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:69)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:181)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:138)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:83)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Projects/Test/testdb.mv.db [1.4.196/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
        at org.h2.mvstore.FileStore.open(FileStore.java:168)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
        ... 36 more
Caused by: java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
        at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
        at java.nio.channels.FileChannel.tryLock(Unknown Source)
        at org.h2.mvstore.FileStore.open(FileStore.java:165)
        ... 39 more
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:95)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:181)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:138)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:83)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
        at org.h2.engine.Database.getPageStore(Database.java:2476)
        at org.h2.engine.Database.open(Database.java:697)
        at org.h2.engine.Database.openDatabase(Database.java:276)
        at org.h2.engine.Database.<init>(Database.java:270)
        at org.h2.engine.Engine.openSession(Engine.java:64)
        at org.h2.engine.Engine.openSession(Engine.java:176)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
        at org.h2.Driver.connect(Driver.java:69)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:69)
        ... 21 common frames omitted
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Projects/Test/testdb.mv.db [1.4.196/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
        at org.h2.mvstore.FileStore.open(FileStore.java:168)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
        ... 36 common frames omitted
Caused by: java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
        at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
        at java.nio.channels.FileChannel.tryLock(Unknown Source)
        at org.h2.mvstore.FileStore.open(FileStore.java:165)
        ... 39 common frames omitted
INFO  - Started Main in 1.434 seconds (JVM running for 1.876)

I'm pretty certain nothing else is actually accessing or locking the db except Schemaspy, because switching back to single schema mode works fine.

## Possible Solution
Fix the connections to run serially, as only a single connection to an embedded db is permitting and schemaspy appears to be connecting in parallel?

I tried the all option and the dbthreads=1 options, same result.

## Steps to Reproduce (for bugs)
1. Create an H2 file db with multiple schemas.
2. Attempt to run schemaspy against it using schemas or all options

## Context
Windows 10, schemaspy 6.0.0-rc2, H2 1.4.196, java 1.8.171

**Comment by npetzall** [comment] 2018-07-30 07:18
Hi, I think the problem is that a connection hasn't been closed. It does some Metadata collection before each individual schema. Simplest fix is probably to close it. But sharing would probably be the best.

**Comment by npetzall** [comment] 2018-07-30 09:50
I currently don't have time to test or do research, but could you try with the snapshot version. We did a change so that same driver would be used. Since there shouldn't technically be a problem to access one file when the same object holds the lock. In rc2 I think there will be two different drivers trying to open the same file which won't work acquiring two different locks.

**Comment by npetzall** [comment] 2018-07-30 21:16
This was fixed with PR #246 and the issue was #129 
So it works if you use the snapshot version, link available in the readme.

The issue was that two drivers were created in different classloaders. So they didn't know of each other and in that case it tried to open the file again instead of using an existing filehandler.

http://www.h2database.com/html/features.html#connection_modes
> In embedded mode, an application opens a database from within the same JVM using JDBC. This is the fastest and easiest connection mode. The disadvantage is that a database may only be open in one virtual machine (and class loader) at any time. As in all modes, both persistent and in-memory databases are supported. There is no limit on the number of database open concurrently, or on the number of open connections.

**Closed** 2018-07-30 21:16 UTC
Labels: fixed in master

**Comment by tresat** [comment] 2018-08-01 16:35
Just checked out the latest, built and ran it with multiple schemas and everything is working great now.  Thank you!

**Comment by npetzall** [comment] 2018-08-01 16:44
There is a link to a pre-built snapshot https://github.com/schemaspy/schemaspy/blob/master/README.md#latest-build
