### ISSUE TITLE
Release jar on jitpack on maven central

### ISSUE THREAD

**Issue by adriens** [schemaspy/schemaspy#445] opened 2018-10-29 21:23 UTC
# Feature motivation

It could be convenient for packager to be able to get the jar straight from maven repos. Hence, releasing on maven central or even more easier on jitpack, could make this possible.

## Expected Behavior

On each release, deliver the jar on maven repo in addition to providing it to the Github release page.

## Current Behavior

Jar only available on Github release page.

## Possible Solution

Relase on central or even easier on jitpack

## Your Environment

Not applicable.

**Comment by npetzall** [comment] 2018-10-29 21:33
Duplicate of #157 
And jitpack requires nothing but a public repo which this is. So you're able to use it right of the bat.

Note #157 also contains discussions about breaking SchemaSpy into modules, so you don't need the commandline interface parts when embedding(which contains spring-boot for instance).

**Closed by npetzall** 2018-10-29 21:33 UTC

**Comment by npetzall** [comment] 2018-10-29 21:35
https://jitpack.io/#schemaspy/schemaspy
