### ISSUE TITLE
Can schemaspy take the SQL dump in stead of connecting to a SQL server?

### ISSUE THREAD

**Issue by dopeddude** [schemaspy/schemaspy#631] opened 2019-12-12 16:57 UTC
Schemaspy is a great tool :))

**Enhancement/Feature Request:**

I am working on a project where we define our database entity definitions and relationships in the yaml files. During our cross functional team meetings/discussions for a better understanding of these relationships I am doing the followings:

1. I parse those yaml files and generate sql files.
2. I load this sql files to postgresql server.
3. I use schemaspy to generate the html documentation from the above postgresql server.

## Expected Behavior
I was just wondering if schemaspy could read from the sql dump/file as produced from step#1 and do the job.

## Current Behavior
The step#2 seems an overload where I have to have a postgresql server only for this sake. 

## Possible Solution
NA

## Steps to Reproduce (for bugs)
NA

## Context
NA

## Your Environment
NA

**Comment by npetzall** [comment] 2020-01-14 22:24
This is a duplicate of #584.

But
We have the schemameta file/files that can augment a database. But I still think it requires a running database.
I've had been pondering and wanting to make it possible to supply schemaspy with other inputs. Like xml or json (currently schemaspy can produce xml output. however it can't be used as input). Due to lack of time and priorities this hasn't been done.

But if that was to be implemented we could probably output yaml or read yaml instead.

As for you problem it's sort of a bother, but I hope you have automated it, using ci and docker.

**Closed** 2020-02-28 23:38 UTC
Labels: duplicate
